spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/digi?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    #password: root1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

user_bank:
  minumumBalance: 5000
  message:
    success: your account has been created successfully.Account number
    fail: Account creation failed. Please contact your bank.
    lessAmount: Account balance is low, minimum deposit is 5000
    hello: Hello
    str: ","
    emptySpace: " "


